### ISSUE TITLE
Set key binding for this action

### ISSUE THREAD

**Issue by honzaprevratil** [lawrence-laz/GoToSameDirectoryInOtherPane#1]
Hi,
can you please add `Key Bindings.json` file for easier customization of the shortcut?
It took me a while to figure it out, how to add shortcut for this action.
I think, It would be easier for others too.
Thanks!

I just added `Key Bindings.json` file to root with this content, and it worked straight forward, after reloading.
`[
	{ "keys": ["Ctrl+m"], "command": "go_to_same_directory_in_other_pane" }
]`

**Comment by lawrence-laz** [comment]
Hi, definitely! Added, thanks for suggestion. 🙂
